---
# All base configurations can be found in the GameMain.java file
# To reset this file to base configurations, simply delete this file and run the game.
gameMode: permadeath
zoned: false
scoreTime: 75000000.0
rewardValue: 1
boundaryWidth: 60f

playerWidth: 40f
playerHeight: 40f
playerSpeed: 10f
startingY: 70f

obstacleDistribution: uniform
waveTime: 1000000000.0
obstacleWidth: 60f
obstacleHeight: 20f
obstacleSpeed: 10f
obstacleSpawnHeight: 700f
obstacleAccelerationBoolean: false
obstacleAccelerationRate: 0f


### Config Notes ###
#
## boundaryWidth #
# boundaryWidth is the width of the margins to the left and right
# of the play field.
#
## playerSpeed #
# playerSpeed is for continuous movement only. 
# You cannot change the speed of the zoned game mode.
#
## startingX #
# startingX is not configurable. It is always the middle of the screen.
#
## startingY #
# startingY represents the vertical start position of the player.
# The sprite will be drawn such that its bottom side corner is at startingY.
#
## Wave Time #
# The amount of time (in nanoseconds) between waves.
# waveTime must end in ".0" for the parser to recognize it as a Double, 
# which is subsequently converted to a long as the parser is unable to recognize
# longs on its own.
#